from django.conf.urls import include, url

from . views import *

from rest_framework import routers

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'user-level', UserlevelViewSet)
router.register(r'user-profile', UserProfileViewSet)
router.register(r'evaluations', EvaluationsViewSet)
router.register(r'person-reference', PersonReferenceViewSet)
router.register(r'birth-place', BirthPlaceViewSet)
router.register(r'nationality', NationalityViewSet)
router.register(r'vessel-name', VesselNameViewSet)
router.register(r'vessel-type', VesselTypeViewSet)
router.register(r'civil-status', CivilStatusViewSet)
router.register(r'mariner-status', MarinerStatusViewSet)
router.register(r'colleges', CollegesViewSet)
router.register(r'degree', DegreeViewSet)
router.register(r'high-schools', HighSchoolsViewSet)
router.register(r'vocationals', VocationalsViewSet)
router.register(r'primary-schools', PrimarySchoolsViewSet)
router.register(r'relationship', RelationshipViewSet)
router.register(r'rank', RankViewSet)
router.register(r'coc-rank', COCRankViewSet)
router.register(r'land-position', LandPositionViewSet)
router.register(r'engine-type', EngineTypeViewSet)
router.register(r'manning-agency', ManningAgencyViewSet)
router.register(r'cause-of-discharge', CauseOfDischargeViewSet)
router.register(r'region', RegionViewSet)
router.register(r'municipality', MunicipalityViewSet)
router.register(r'barangay', BarangayViewSet)
router.register(r'sources', SourcesViewSet)
router.register(r'specifics', SpecificsViewSet)
router.register(r'reasons', ReasonsViewSet)
router.register(r'status', StatusViewSet)
router.register(r'english', EnglishViewSet)
router.register(r'dialect', DialectViewSet)
router.register(r'bank', BankViewSet)
router.register(r'branch', BranchViewSet)
router.register(r'passport-place-issued', PassportPlaceIssuedViewSet)
router.register(r'sbook-place-issued', SBookPlaceIssuedViewSet)
router.register(r'us-visa-place-issued', USVisaPlaceIssuedViewSet)
router.register(r'schengen-visa-place-issued', SchengenVisaPlaceIssuedViewSet)
router.register(r'yellow-fever-place-issued', YellowFeverPlaceIssuedViewSet)
router.register(r'license-place-issued', LicensePlaceIssuedViewSet)
router.register(r'coc-place-issued', COCPlaceIssuedViewSet)
router.register(r'training-place-issued', TrainingPlaceIssuedViewSet)
router.register(r'issuing-authority', IssuingAuthorityViewSet)
router.register(r'zip', ZipViewSet)
router.register(r'flags', FlagsViewSet)
router.register(r'training-certificates', TrainingCertificatesViewSet)
router.register(r'principal', PrincipalViewSet)
router.register(r'training-center', TrainingCenterViewSet)
router.register(r'trade-area', TradeAreaViewSet)
router.register(r'propulsion', PropulsionViewSet)
router.register(r'current-address', CurrentAddressViewSet)
router.register(r'permanent-address', PermanentAddressViewSet)
router.register(r'personal-data', PersonalDataViewSet)
router.register(r'spouse', SpouseViewSet)

urlpatterns = [
	url(r'^', include(router.urls)),
]