# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mariners_profile', '0123_auto_20151014_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cocplaceissued',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cocrank',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flags',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='landposition',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='licenseplaceissued',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='manningagency',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='passportplaceissued',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='principal',
            name='company_standard',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rank',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sbookplaceissued',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='schengenvisaplaceissued',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trainingcertificates',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trainingplaceissued',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usvisaplaceissued',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vesseltype',
            name='company_standard',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='yellowfeverplaceissued',
            name='company_standard',
            field=models.NullBooleanField(default=True),
        ),
    ]
